file_format: "1"
id: fifi
name: Fifi
type: shield
url: https://github.com/foostan/crkbd/
requires: [pro_micro]
exposes: [i2c_oled]
features:
  - keys
  - display
siblings:
  - fifi_left
  - fifi_right